### ISSUE TITLE
Tagging lore 

### ISSUE THREAD

**Issue by beng** [christhompson/loredb#33]
it would be nice if lore could be tagged. doing so would allow users to organize lore and also allow users to filer lore by topic(s). i should be able to add `N` (some reasonable number) tags when creating new lore as well as add `N` tags to existing lore.

**Comment by christhompson** [comment]
Current support:
- `loredb tag <lore-id> <tag> [<tag> ...]`
- `loredb get-tag <tag> [-n num]`
- `loredb remove-tag <lore-id> <tag>`

So adding lore and adding tags to it is still a two-step process, but otherwise this is now supported.
